[project]
name = "gestos"
version = "0.1.0"
description = "Controle do Omarchy por gestos de mão na webcam"
authors = [
    { name = "GustavoRochaSilva", email = "gusttavorochasilva@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "mediapipe==0.10.21",
]

[project.scripts]
gestos = "gestos:main"
gestos-calibrar = "gestos.calibrar:main"
gestos-avaliar = "gestos.avaliar:main"

[build-system]
requires = ["uv_build>=0.12.12,<0.13.0"]
build-backend = "uv_build"
